spring.application.name=project

#H2 in-memory database usage
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Key used for encryption is put in here so it wont apear in the code
app.security.encryption.key=8x/w/bO3B+y/Lz1gZq8uP6H9h+L5mQ8uR4aT7vW2yE4=

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=MoodleCalendarNoReply@gmail.com
spring.mail.password=wirk wqrs llzd ohbk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true